#!/usr/bin/env bash
# This script changes the IP resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Update /etc/hosts to change localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Update /etc/hosts to resolve facebook.com to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/' /etc/hosts

