#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine

# Using the 'ip' command to display the active IPv4 addresses
ip -4 addr show | grep inet | awk '{print $2}' | cut -d/ -f1

